//
//  Config.swift
//  HypnoFlow
//
//  Secrets / environment configuration. This file is gitignored — it is NOT
//  committed to source control. Fill in your own values on each machine you
//  build on (see ios/CONFIG.md).
//

import Foundation

enum Config {
    /// ElevenLabs API key for direct text-to-speech. When non-empty, narration
    /// is generated by calling ElevenLabs directly. Leave "" to use the Rork
    /// proxy below instead.
    static let ELEVENLABS_API_KEY = "07dce7c4b9ca116a9702855da571d3c1a010a7458e5cda8655418aa46a28d9c1"

    /// Rork AI proxy base URL (used for script generation, and for narration
    /// when ELEVENLABS_API_KEY is empty).
    static let EXPO_PUBLIC_TOOLKIT_URL = ""

    /// Rork AI proxy bearer secret.
    static let EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY = ""
}
